%% FigGenForNearOptPaper.m
% Matlab 2013b Script to generate Figures in the paper
% 
% David E. Rosenberg (in review) "Near-optimal alternative generation,
% visualization, and interaction for water resources decision making".
% Water Resources Research. Submitted August 2014
%
% The script automatically generates Figures 1, 2, 3, and 5.
% The script also provides in-comment instructions to interactively produce
%   - Figure 4 from Figure 3
%   - Figure 5 from Figure 3
%   - Figure 6 from Figure 5
%   - Figure 7 from Figure 3
%
% #####################
%   Programmed by David E. Rosenberg
%   August 2014
%   
%   Dept. of Civil & Env. Engineering and Utah Water Research Lab
%   Utah State University
%   david.rosenberg@usu.edu
%
%   Citation:
%   David E. Rosenberg (in review) "Near-optimal alternative generation,
%   visualization, and interaction for water resources decision making".
%   Water Resources Research. Submitted August 2014

%   Licensing:
%   This code is distributed AS-IS with no expressed or implied warranty regarding the claimed functionality. The entire code or parts 
%   may be used for non-commercial purposes so long as the use is cited per the citation above. Use for any commercial purpose requires 
%   prior written permission from the author.
%
%   Bug Reports and Feedback:
%   Bug reports and Feedback are much appreciated. Please submit via the the issue tracker on the
%   GitHub repository where you downloaded this file.
%   Note that while much appreciated, there is no promise of when, or if, a reported bug will be corrected.

%% Generating the Figures

% #### Figure 1 ####
% Optimal solution (blue circle), single maximally-different alternative produced 
% by the Modelling to Generate Alternatives method (purple triangle), and full 
% near-optimal region (green shading) for an example two-decision problem with a 
% quadratic objective function, four linear constraints, and tolerable deviation of ?=1.80.
%
% After the figure loads, use the crosshairs to mouse-over and label the
% objective function contours. Click enter to finish.
%
Fig1_FeasibleNearOptCompare([1 -20 5 0 100], [3 2;0 1], ['<' '<'], [12 4]','min',1.8,14, {'Decision Variable 1 (X_1)' 'Decision Variable 2' '(X_2)'},20,0,1);
set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 1. Near-optimal region for example problem');

%%
% #### Figure 2 ####
% Point (pink), linear (blue), and other topological relations in Cartesian (left) and 
% Parallel (right) coordinate systems.
%
Fig2_CartParCompare(14,1,{'Decision 1' 'Decision 2' sprintf('%s\n%s','Objective','Function')});
set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 2. Compare Cartesian and Parallel Coordinate plots');

%%
% #### Figure 3 ####
% Phosphorus removal strategies for Echo Reservoir, Utah recommended by
% (i) the optimal solution (thick black line), (ii) five maximally-different Modelling to Generate
% Alternatives (purple lines) and (iii) 2,500 stratified sampled near-optimal alternatives generated 
% by the new tools (green lines). The stratified alternatives show managers can flexibly target any 
% practice to any source in any sub-watershed and still keep removal costs within 10% of the cost of the optimal solution
%
[mResult nO vParams] = LoadEchoGamsResults('WQNE_outG6.gdx',3,2500,0);
set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 3. Compore optimal solution, MGA, and near-optimal region for Echo Reservoir problem');

%%
% #### Figure 4 ####
% Exploring the effects of interactively setting sliders to not stabilize stream banks in Chalk Creek 
% (first checked axis) but shift and increase phosphorus removal in the Weber above and below Wanship 
% sub-watersheds (second and third checked axes). Sliders show the range of allowable phosphorus removal 
% for each practice given slider settings while purple lines show the family of alternatives generated by 
% the slider settings.
%

% Interactive Steps To Shift, Increase stream bank stabilization
%   1. Generate Figure 3. At the commnad prompt paste:
%           >> [mResult nO vParams] = NearOptimalLP2('WQNE_outG6.gdx',3,2500,0);
%   2. Once the figure finally loads, show the control panel. From the Controls menu=>uncheck Hide all
%       controls
%   3. Click the Interact tab
%   4. From the Controls Menu=>Sliders=>uncheck Hide sliders (show them).
%       Sliders will appear on the plot all set to minimum allowable values
%   5. Check the box for Stabilize stream banks in Chalk Creak (set level to zero).
%   6. Set the slider to Stabilize Stream banks in the Weber below Wanship
%       sub-watershed to 3150 kg. Or in the Filter Exisiting Alternatives box,
%       enter 3150 in the Set value text box for the axes. Ranges for other sliders
%       will update.
%   7. Set the slider for Stabilize stream banks in the Weber above Wanship
%       sub-watershed to 3,700 kg. Again, other sliders will update.
%   8. In the Generate New Alternatives box, click the Generate button. The
%       command window will update with info on the alternative generation. A new group of
%       lines will add to the plot (in purple).
%   9. Format the plot to compare to previous settings.
%        - Click the Display tab
%        - Enter a new name for the new second group in purple (e.g, 'Stream
%        bank stabilization' 
%        - Change the Ord (Order) for the group from 2 to 3.
%        - Similarly, change the order for the MGA group to 2 and uncheck
%        the box at the right (do not show the MGA group)
%        - Click the Reorder Groups button
%   10. Retitle the figure. At the command promt, paste:
%        set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 4. Shifted, increased stream bank stabilization');
%        
%   

%%
% #### Figure 5 ####
% Comparing pareto solutions (orange lines and triangles), maximally-different Modelling to Generate Alternatives 
% (purple lines and circles), and stratified sampled near-optimal alternatives (green lines and crosses) for an 
% updated multi-objective formulation in linked objective-decision spaces (main parallel coordinate plot) and 
% objective space (inset Cartesian plot).
%
% Automatically Generate
[mResult nO vParams] = LoadEchoGamsResults('WQNE_outG6.gdx',3,2500,1); %same as Figure 3 but last parameter changed to 1
set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 5. Comparisons for multi-objective problem');

% Alternative interactive steps to streamline the process to add a new objective and update the model formulation
%   1. Generate Figure 3. At the commnad prompt paste:
%          >> [mResult nO vParams] = NearOptimalLP2('WQNE_outG6.gdx',3,2500,0);
%   2. Once the figure finally loads, click the Update Formulation menu,
%      and select Add new objective(s).
%   3. In the Add New Objective(s) window, enter data for a single new
%      objective to maximize the mass of phosphorus removed. Enter the inputs
%      as:
%        - Number of new objectives: 1
%        - New objective function coefficients: ones(1,39)
%        - Labels: {'Phos. removed'}
%        - Units of measurement: {'kg'}
%        - Direction: {'max'}
%        - Near-optimal tolernace: 0.5
%        - Plot limits: [0; 18000]
%
%      Here, there is one new objective, the coefficients represent a row
%      vector of ones where every decision variable contributes equally to the
%      mass of phosphorus removed, the objective will be labeled 'Phos. removed' and quantified in kg, a new
%      constraint will be added to the formulation that requires removal
%      greater than 0.5*the maximumal removal (to prevent interaction with the existing near-optimal constraint
%      for the first cost removal objective, and the new objective will be
%      plotted between the limits of 0 and 18000 kg.
%
%        - At the bottom, click OK and Matlab will update the model
%          formulation, sample new alternatives, and add them as purple lines to the plot.
%
%   4. Format the plot.
%        - From the Controls menu, uncheck Hide all controls. The controls
%          menu will appear at the right.
%        - Click the Display tab. At the bottom is a listing of the groups.
%        - Enter new numbers in the Ord box so the group orders become:
%           + 3 Near-optimal (the original alternatives sampled from the single-objective formulation)
%           + 1 Near-optimal_Resample (the new alternatives sampled from the multi-objective formulation)
%           + 2 MGA (Modeling to generate alternatives loaded when Figure 3 was generated)
%          Then click the Reorder Groups button. The Near-optimal group
%          will now appear third in the list in peach and the lines on top.
%        - Merge the NewOpt (optimal solution for the new objective) and Optimum (optimum solution for the original objective)
%          groups into a single Pareto group
%           + Unclick all the groups except those groups.
%           + Rename the first group Pareto
%           + Click the Merge Checked Groups button
%        	+ Set the Highlight Group Button to Pareto and the two pareto
%        	solutions will plot on top in thick black.
%        - From the Controls menu, select Show inset plot to make the
%           pareto-tradeoff inset plot visible. The plot shows the two objectives, two
%           pareto solutions at the corners and the newly sampled alternatives
%           (green triangels) well distrubted in the pareto objective space.
%           The alternatives sampled originally for only one objective (peach crosses) are less well
%           distributed in the pareto space.
%        - Uncheck the 3rd group (peach Near-optimal) and click the Show
%           Checked Groups button. Only the pareto solutions, newly-sampled and
%           MGA alternatives will show.
%    5. To load more intermediary pareto solutions between the two
%       extreme solutions:
%        - From the Plot Data menu, select Save data to save the model data
%           back to the Base Workspace.
%        - At the Matlab command prompt, retrieve the model constraints, objective function, and near-optimal data from
%           parameters #36, 38, and 40 in no_vargs. i.e.,
%
%            >> Amat = no_vargs{36};
%            >> Brhs = no_vargs{38};
%            >> cFunc = no_vargs{40};
%            >> Tolerance = no_vargs{4};
%            >> NearOptConstraint = no_vargs{74};
%            >> OptSols = no_vargs{76};
%
%        - Update the right-hand side coefficients for the rows that
%        represent near-optimal tolerance constraints:
%
%            >> Brhs(NearOptConstraint) = sign(Brhs(NearOptConstraint)).*Tolerance'.*diag(no_mObjs(OptSols,:))
%
%             The sign preserves the direction of the optimization and the
%             diag pulls out the diagnal value from the objective function
%             value.
%
%        - Use the Matlab linprog function to calculate pareto-optimal
%           solutions such as by the constraint method or another pareto solution generation method.
%        - Organize results from the prior step into two matrices where
%           each of the nNew rowd represents a pareto solution.
%           + mObjPareto : nNew x 2 (values for objective functions 1 and 2
%               in columns 1 and 2)
%           + mDecPareto : nNew x 39 (values for each decision variable in
%               columns 1..39).
%        - Back in the Figure window, from the Plot Data menu, select Load
%        Data.... In the Load Data window that opens, enter:
%           + New objective function values: mObjPareto
%           + New decision varaible values: mDecPareto
%           + Group name(s): 'Pareto'
%
%           + Then click OK and the new pareto solutions will be shown on
%           the plot.


%%
% #### Figure 6 ####
% Sub-region of near-optimal alternatives that remove large amounts of phosphorus (purple lines and markers) but 
% use more varied locations and practices  than pareto solutions (orange lines and triangles).   
%
 
% Interactive Steps to generate alternatives that remove a lot of phosphorus
%   1. Generate Figure 5. At the commnad prompt paste:
%          >> [mResult nO vParams] = NearOptimalLP2('WQNE_outG6.gdx',3,2500,1);
%   2. Once the figure finally loads, click the Interact tab
%   3. Just above the Generate New Alternatives box, enter 0.65 for the
%       Subspace Error (this setting will select alternatives that have
%       values of the (Set value +/- Error). Here error is measured as a
%       fraction of the tick spacing
%   4. From the Controls Menu=>Sliders=>uncheck Hide sliders (show them).
%       Sliders will appear on the plot all set to minimum allowable values
%   5. Set the slider Phos. Removed axis to it's upper extent.
%       Or in the Filter Exisiting Alternatives box,
%       enter 14450 kg in text box for the axes. Other the ranges for other sliders
%       will update.
%   6. In the Generate New Alternatives box, click the Generate button. The
%       command window will update with info on the alternative generation. A new group of
%       lines will add to the plot (in purple).
%   7. Format the plot to compare to previous settings.
%        - Click the Display tab
%        - Enter a new name for the new second group in purple (e.g, 'Large phos. removal' 
%        - Change the Ord (Order) for this group from 2 to 3.
%        - Similarly, change the order for the MGA group to 2 and uncheck
%           the box at the right (do not show the MGA group)
%        - Click the Reorder Groups button
%        - Hide the sliders (Controls menu=>Sliders=>check Hide sliders
%    8. Retitle the figure. At the command prompt, enter:
%           >> set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 6. Alternatives that remove lots of phosphorus');
%   

%%
% #### Figure 7 ####
% Progressive effects of relaxing the near-optimal tolerance parameter on ranges of allowable phosphorus
% removal for each practice. Green shading redundantly denotes removal cost and varies in 5% increments
% from dark green (optimal cost) to light green (125% of optimal cost).
%    
% Interactive Steps To Generate alternatives in an expanded near-optimal region
%   1. Generate Figure 3. At the commnad prompt paste:
%          >> [mResult nO vParams] = NearOptimalLP2('WQNE_outG6.gdx',3,2500,0);
%   2. Once the figure finally loads, click the Interact tab
%   3. Set the Near Optimal Tolerance to 1.25
%   4. In the Generate New Alternatives box, click the Generate button. The
%       command window will update with info on the alternative generation. A new group of
%       lines will add to the plot (in purple).
%   5. Format the plot to compare to previous settings.
%        - Click the Display tab
%        - Enter a new name for the new second group in purple (e.g, 'Tolerance 1.25' 
%        - Change the Ord (Order) for the 2nd purple group from 2 to 1.
%        - Similarly, change the order for the first green group from 1 to
%        2ide it)
%        - Uncheck the MGA group (to h
%        - Click the Reorder Groups button and the Tolerance 1.25 group
%        will plot behind the Near-optimal group and it possible to see
%        the effects of expanding the near-optimal tolerance from 1.10 (original) to 1.25 (new group).
%   6. To show the color ramp of effects of all changes from 1.0 to 1.25:
%        - Click the Color Ramp tab
%        - Enter the # Color classes as 5
%        - Set Direction to Descend
%        - Check the box associated with the Removal Cost axis (far left
%        axis)
%        - On the Color Ramp tab, check the box labeled Ramp color. The
%           color ramp will appear. Additionally, a checkbox for each color band
%           will appear on the Color Ramp tab. Uncheck to hide the traces
%           in the specified band.
%    7. Re-title the figure. Run the command at the command promp:
%         >>  set(gcf,'NumberTitle','off','Name','Near-Optimal Figure 7. Expanded near-optimal region');      

msgbox('Finished auto-generating Figures 1, 2, 3, and 5. To interactively create Figures 4, 6, and 7 from Figures 3 and 5, see the further steps for each figure listed as comments in the script.','Title','Progress Report')
